### ISSUE TITLE
Logfile not being written

### ISSUE THREAD

**Issue by Mike-HRC** [moschotto/OpenTX_GPS_Telemetry#22] opened 2022-02-15 19:15 UTC
Hi Mosch, as I mentioned on YouTube, I am trying to get your GPS lua and GPS Stats viewer working so that I can find my planes if they get lost  - I have downloaded the scripts onto my RadioMaster Tx16S running 2.3.14 OpenTx.  The GPS lua draws the screen and after a while says "No GPS fix" - it is getting GPS data, but does not start writing to the log (even though the GPS sensor data gets a fix).

I have got a /LOGS/ folder set-up and even created a dummy GPSpositions.txt file - but this does not get written to.

I have used this GPS sensor (BN-220) before (for a logger) and it works fine, I have tried it on a very simple lua that just writes to the screen and that was working as well, so I believe that the sensor is working properly.

Please let me know any other info that will help.

Thanks for your help with this,
Mike

**Comment by moschotto** [comment] 2022-02-15 19:37
Thanks - just tried to reproduce but I can’t. Can you please make sure that all sensors have been discovered under telemetry in the radio or even delete it an rediscover?

Especially GPS, speed and alt!

logfile will be generated only if there’a a valid gps signal…

thanks

**Comment by Mike-HRC** [comment] 2022-02-15 19:47
Yep - I get all 3 in the sensor list, and can use GPS as a value field in a widget
![image](https://user-images.githubusercontent.com/62241833/154137342-b44ac321-d45a-43f7-aa78-d9b5246fe8a3.png)

![image](https://user-images.githubusercontent.com/62241833/154137412-abf231ff-777d-4411-896a-5e7956fae58d.png)

**Comment by moschotto** [comment] 2022-02-15 19:55
Sorry I forgot to add SATS… how many satellites do you see

**Comment by Mike-HRC** [comment] 2022-02-15 19:56
I put them on the same screen for confirmation

![image](https://user-images.githubusercontent.com/62241833/154138806-ac31efc2-d7a7-476a-855e-9a292dd0841d.png)
![image](https://user-images.githubusercontent.com/62241833/154138847-f76eb3d0-0859-4f4d-b546-3359c78a581a.png)

**Comment by Mike-HRC** [comment] 2022-02-15 19:57
> Sorry I forgot to add SATS… how many satellites do you see

I'm not sure - your widget says 0, but the sensor seems to have the GPS position.

Please understand - I'm sure that it will be something stupid that I have not done or done wrong - I'm not doubting your work :)

**Comment by moschotto** [comment] 2022-02-15 19:58
Sorry I meant when you check them in the telemetry sensor page because logging etc starts:

if (tonumber(wgt.gpsSATS) >= 5) then


satellites are represented etiher as "TMP2" or as "Sats"


![Screenshot 2022-02-15 210233](https://user-images.githubusercontent.com/10543292/154140077-ee60fecc-6a48-41eb-9197-7f0ef01ae9eb.jpg)

SmartPort (S.Port) Example 1012: -> 1= GPS fix 0=lowest accuracy 12=12 active satellites

**Comment by Mike-HRC** [comment] 2022-02-15 20:00
I didn't know that it was shown there - I'll just check

**Comment by Mike-HRC** [comment] 2022-02-15 20:07
That must be it - I'm using a Arduino based sensor that can take inputs from things like pack voltage, current, temperatue, motor speed etc. etc. and feed them through into S.port format for FrSky receivers - possibly he is not passing all GPS field values through

**Comment by moschotto** [comment] 2022-02-15 20:14
yes that's it - what kind of sensor/arduino kind of thing is it?

BTW here the offical betaflight doc:

https://github.com/betaflight/betaflight/blob/master/docs/Telemetry.md

=> check for TMP2

**Comment by Mike-HRC** [comment] 2022-02-15 20:21
I use Pro Mini, but it will work with others - I've been using them for years on my helis as originally it took a telemetry feed from HobbyWing ESCs for things such as RPM, Temp, Current (on bigger ESCs) etc. as well as Phase sensors for RPM from other ESCs, then other bits and pieces got added as well as support for other ESCs and other Receivers (FlySky etc.).

This is the project https://github.com/dgatf/msrc for a few dollars of arduino, plus a £6 GPS I can get GPS into the TX16S as well as the lipo voltage etc. etc. - just not the number of sats it seems :)

**Comment by moschotto** [comment] 2022-02-15 20:24
excactly because it doesn't support SATS:

GPS:

    GPS Lat/Lon: GPS (0x800)
    GPS altitude: GAlt (0x820)
    GPS speed: GSpd (0x820)
    GPS compass: Hdg (0x840)
    GPS date/time: Date (0x850)

smartport.cpp seems to be missing the satP values. Open an issue at his repository and ask for satellite support:

Either transmitted as SATS or as TMP2


https://github.com/dgatf/msrc/blob/master/msrc/smartport.cpp

and

https://github.com/betaflight/betaflight/blob/master/docs/Telemetry.md


![Screenshot 2022-02-15 213712](https://user-images.githubusercontent.com/10543292/154145090-7946c814-35db-41bf-87cd-97605bcbd9b5.jpg)

**Comment by Mike-HRC** [comment] 2022-02-15 20:34
Thank you so much for your help Moscho - sorry to waste your time.  I'll see if Daniel can include the number of Sats in the data stream. 

Is there anything that I should do to close this issue report or on YT for you to make obvious that it is my issue not yours?

**Comment by moschotto** [comment] 2022-02-15 20:35
no i'm closing it. good to see that's not my issue ;)

**Closed as completed** 2022-02-15 20:35 UTC

**Comment by Mike-HRC** [comment] 2022-02-15 23:00
Daniel made the changes to add a field with the number of satelites locked - and it's all good now - thanks again, really appreciate your help, and the excellent widget
![moscho 2](https://user-images.githubusercontent.com/62241833/154164178-11653353-6af3-4510-b56e-e64f6d368059.jpg)
