### ISSUE TITLE
Getting a syntax error when i click on the GPS stats lua

### ISSUE THREAD

**Issue by Chillinfpv** [moschotto/OpenTX_GPS_Telemetry#47] opened 2024-04-16 11:13 UTC
So I just added the GPSpositions.txt file to the logs file and now I'm getting a syntax error bad argument #1 to gsub string expected got nill. I have all the new sensors and they're working fine. I get gps coordinates in the telemetry screen but not in the telemetry lua. It only has the number of satellites. It's not updating the home position.

**Comment by Chillinfpv** [comment] 2024-04-16 11:14
![20240416_032543](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/167156065/9c6085c2-c110-4802-a9d7-15863a6842bf)
![20240415_172408](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/167156065/2613767f-4b47-4390-a1b1-4e9e9655cc7d)
![20240415_204237](https://github.com/moschotto/OpenTX_GPS_Telemetry/assets/167156065/c1372e29-f1aa-4836-83f3-bf7124fb5500)

**Comment by moschotto** [comment] 2024-04-16 19:19
duplicate of https://github.com/moschotto/OpenTX_GPS_Telemetry/issues/46

**Closed as completed** 2024-04-16 19:19 UTC
